import os
import json
import requests
from github import Github
import sys

# Ensure the core module can be found if script is run from project root
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from core.pr_reviewer import PRReviewer
except ImportError as e:
    print(f"Error importing PRReviewer: {e}")
    sys.exit(1)

def main():
    # 1. Grab environment variables
    github_token = os.getenv("GITHUB_TOKEN")
    google_api_key = os.getenv("GOOGLE_API_KEY")
    event_path = os.getenv("GITHUB_EVENT_PATH")

    if not github_token:
        print("Error: GITHUB_TOKEN is missing.")
        sys.exit(1)
    if not google_api_key:
        print("Error: GOOGLE_API_KEY is missing. Add it to Repository Secrets.")
        sys.exit(1)
    if not event_path:
        print("Error: GITHUB_EVENT_PATH is missing. Are we running in an Action?")
        sys.exit(1)

    # 2. Parse the GitHub event payload
    with open(event_path, "r", encoding="utf-8") as f:
        event_data = json.load(f)

    # Validate it's a pull request
    if "pull_request" not in event_data:
        print("Not a pull request event. Exiting.")
        sys.exit(0)

    repo_name = event_data["repository"]["full_name"]
    pr_number = event_data["pull_request"]["number"]

    # 3. Authenticate with PyGithub
    g = Github(github_token)
    repo = g.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    # 4. Get the PR diff
    # We can get the diff by requesting the diff URL with the correct headers
    diff_url = pr.diff_url
    headers = {"Authorization": f"token {github_token}", "Accept": "application/vnd.github.v3.diff"}
    response = requests.get(diff_url, headers=headers)
    
    if response.status_code != 200:
        print(f"Error fetching diff: {response.status_code} - {response.text}")
        sys.exit(1)
        
    diff_text = response.text

    if not diff_text.strip():
        print("Diff is empty. Nothing to review.")
        sys.exit(0)

    # 5. Review the diff using Gemini 2.5
    print("Initializing AI PR Reviewer...")
    reviewer = PRReviewer()
    
    print("Analyzing diff...")
    ai_review_comment = reviewer.review_diff(diff_text)

    # 6. Post the comment back to the PR
    print("Posting review comment to PR...")
    # Add a friendly signature
    final_comment = f"🤖 **AI Code Review (Gemini 2.5)**\n\n{ai_review_comment}\n\n---\n*Auto-generated by AI Code Reviewer Action*"
    
    pr.create_issue_comment(final_comment)
    print("Review posted successfully!")

if __name__ == "__main__":
    main()
